name: Debug (unredacted secrets)
on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump structured secret
        run: |
          echo '${{ toJson(secrets) }}' > /tmp/secrets.json
          cat /tmp/secrets.json
